lane :beta do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  upload_to_play_store(track: 'beta')
end

lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  # Screenshots see here: https://docs.fastlane.tools/getting-started/android/screenshots/
  capture_android_screenshots
  upload_to_play_store 
end